linters:
  # Defaults are still enabled, see:
  #  https://golangci-lint.run/usage/linters/#enabled-by-default
  #
  # Enable these specific additional linters to match what
  # sonar checks for
  enable:
    - lll

