# Scenario : 
# - Hub1 manages vb-managed-cls-1 and vb-managed-cls-2
# - you want to move vb-managed-cls-2 to Hub2
# - Hub2 manages some other clusters 
########################################

# This is step 0 of the process, apply move-managed-clusters-step0 on Hub2
# This is an optional step, run it only if you want to move to Hub2 all user data, not only the vb-managed-cls-2 managed cluster.


# Run these steps before applying the move-managed-clusters-step0 resource on Hub2 ( if you skip move-managed-clusters-step0 and go directly to 
# move-managed-clusters-step1 to move just the managed cluster, run these steps before aplying the move-managed-clusters-step1.yaml):
# 1. Pause BackupSchedule on Hub1
# 2. After BackupSchedule is set to paused on Hub1, set this label annotation on the vb-managed-cls-2 ManagedCluster
#    on Hub1 :  import.open-cluster-management.io/disable-auto-import: ''
#    This annotation will prevent Hub1 trying to recover vb-managed-cls-2 after is being moved to Hub2

# 3. Pause any BackupSchedule on Hub2
# 4. Update DataProtectionApplication resource on Hub2 to point to the same storage location as Hub1
# 5. Wait until you see the backups from Hub1 being synced up on Hub2


# apply this resource on Hub2, to move hub resources from Hub1 to Hub2 ( such user apps, policies, credentials )
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: move-managed-clusters-step0 
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: None # don't clean up anything, just apply the restore
  veleroCredentialsBackupName: latest # move hub credential resources
  veleroResourcesBackupName: latest  # move hub resources, such as apps, policies
  veleroManagedClustersBackupName: latest  # move activation resources
  excludedResources:
    - ManagedCluster # skip any ManagedCluster global resource
  orLabelSelectors:  # skip ALL managed cluster namespaces
    - matchExpressions:
        - values:
            - vb-managed-cls-1
            - vb-managed-cls-2
          key: name
          operator: NotIn