# Scenario : 
# - hub-a manages vb-managed-cls-1 and vb-managed-cls-2
# - you want to move vb-managed-cls-2 to hub-b
# - hub-b manages some other clusters 
########################################

# This is step 0 of the process, apply move-managed-clusters-step0 on hub-b

# Before applying the move-managed-clusters-step0 resource on hub-b:
# 1. Pause BackupSchedule on hub-a
# 2. After BackupSchedule is set to paused on hub-a, set this label annotation on the vb-managed-cls-2 ManagedCluster
#    on hub-a :  import.open-cluster-management.io/disable-auto-import: ''
#    This annotation will prevent hub-a trying to recover vb-managed-cls-2 after is being moved to hub-b

# 3. Pause any BackupSchedule on hub-b
# 4. Update DateProtectionApplication resource on hub-b to point to the same storage location as hub-a
# 5. Wait until you see the backups from hub-a being synced up on hub-b


# apply this resource on hub-b, to move hub resources from hub-a to hub-b ( such user apps, policies, credentials )
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: move-managed-clusters-step0 
  namespace: open-cluster-management-backup
spec:
  cleanupBeforeRestore: None # don't clean up anything, just apply the restore
  veleroCredentialsBackupName: latest # move hub credential resources
  veleroResourcesBackupName: latest  # move hub resources, such as apps, policies
  veleroManagedClustersBackupName: skip  # skip
  orLabelSelectors:  # skip ALL managed cluster namespaces
    - matchExpressions:
        - values:
            - vb-managed-cls-1
            - vb-managed-cls-2
          key: name
          operator: NotIn