#  veleroTtl - optional; deletes scheduled backups after specified time
#  if veleroTtl is not specified, the maximum default value set by velero is used - 720h
# 
# veleroSchedule - cron job to start new acm backups
#
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
  name: schedule-acm
spec:
  veleroSchedule: 0 */6 * * *
  veleroTtl: 240h