#
# This configmap is used by the oadp-hdr-app-install and oadp-hdr-app-backup policies 
# and specifies the configuration required to install velero and create backups 
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: hdr-app-configmap
  namespace: default
data:
  # backupNS is the ns where velero/oadp is installed on the cluster
  # if you change the default value acm-app-backup , make sure you don't use open-cluster-managemenet-backup ns
  # which is reserved by the acm backup and restore operator running on the hub 
  backupNS: acm-app-backup 
  channel: stable-1.1
  subscriptionName: redhat-oadp-operator

## DPA resource configuration
#
  dpaName: dpa-app #DPA resource name
  dpa.provider: aws
  dpa.backup.cloud.credentials.name: cloud-credentials
  dpa.objectStorage.bucket: <bucket>
  dpa.objectStorage.prefix: <folder>
  ## velero resource limits
  dpa.velero.limits.cpu: "2"
  dpa.velero.limits.memory: 1Gi
  dpa.velero.requests.cpu: 500m
  dpa.velero.requests.memory: 256Mi
##

##AWS
  dpa.aws.backup.cloud.credentials: |
    [default]
    aws_access_key_id=<id>
    aws_secret_access_key=<key>
   # define the region where the backup resources ( not PVs, they are stored under the cluster node's region ) should be stored
   # for example dpa.aws.backup.config.region: us-east-1
  dpa.aws.backup.config.region: <region>
# end AWS

## AZURE
  dpa.azure.backup.cloud.credentials: |
    [backupStorage]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.storage.cloud.credentials: |
    [volumeSnapshot]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.backupLocation.resourceGroup: <azure_resource_group>
  dpa.azure.backupLocation.storageAccount: <azure_storage_account_id>
  dpa.azure.backupLocation.subscriptionId: <azure_subscription_id>
  dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
## end AZURE

###### backup schedule resource ###
####################################
  backup.schedule: 0 */1 * * *
  backup.ttl: 240h0m0s
  # list here all applications namespaces you want to backup
  # for example nsToBackup: "[\"pacman-ns\", \"helloworld-pv-ns\"]"
  nsToBackup: "[\"app1-ns\", \"app2-ns\", \"app3-ns\"]" 
######################################
###### end backup schedule resource ###

###### restore resource ###
####################################
  restorePVs: "true"
  # the name of the backup to restore from
  # for example backupName: acm-app-schedule-vb-managed-cls-1-20230208150010
  backupName: <backup-name>
  # list here all apps ns you want to restore from the specified backup
  # for example nsToBackup: "[\"pacman-ns\"]"
  nsToRestore: "[\"app1-ns\", \"app2-ns\"]"
######################################
###### end backup schedule resource ###





