#
# This configmap is used by the oadp-hdr-app-install and oadp-hdr-app-backup policies 
# and specifies the configuration required to install velero and create backups 
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: hdr-app-configmap
  namespace: default
data:
  # backupNS is the ns where velero/oadp is installed on the cluster
  backupNS: open-cluster-management-backup 
  channel: stable-1.1
  subscriptionName: redhat-oadp-operator

# define cloud-credential used to connect to the storage location, base64 encoded string
# for example, for an aws storage location, the credential is in this format
#
# [default]
# aws_access_key_id=<id>
# aws_secret_access_key=<key>
#
  dpa.aws.backup.cloud.credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPTxpZD4KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PTxrZXk+


## DPA resource configuration
#
  #DPA resource name; use the same name for all hubs, the PV cannot be restored if 
  # the BackupStorageLocation resource doesn't have the same name
  # on both backup and restore cluster 
  dpaName: dpa
  dpa.backup.cloud.credentials.name: cloud-credentials
#######
# DPA spec
# below is the spec format for an aws storage
# update this with the DPA format for the type of storage you are using
# values specified with brackets <> should be updated before appliying this configmap
  dpa.spec: "{
  \"backupLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"<us-east-1>\"
        },
        \"credential\": {
          \"key\": \"cloud\",
          \"name\": \"<dpa.backup.cloud.credentials.name>\"
        },
        \"default\": true,
        \"objectStorage\": {
          \"bucket\": \"<bucket-name>\",
          \"prefix\": \"<in-bucket-folder-name>\"
        },
        \"provider\": \"<aws>\"
      }
    }
  ],
  \"configuration\": {
    \"restic\": {
      \"enable\": false
    },
    \"velero\": {
      \"defaultPlugins\": [
        \"openshift\",
        \"aws\"
      ],
      \"podConfig\": {
        \"resourceAllocations\": {
          \"limits\": {
            \"cpu\": \"2\",
            \"memory\": \"1Gi\"
          },
          \"requests\": {
            \"cpu\": \"500m\",
            \"memory\": \"256Mi\"
          }
        }
      }
    }
  },
  \"snapshotLocations\": [
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"default\",
          \"region\": \"<use here ClusterClaim region.open-cluster-management.io value>\"
        },
        \"provider\": \"<aws>\"
      }
    },
    {
      \"velero\": {
        \"config\": {
          \"profile\": \"<east1>\",
          \"region\": \"<us-east-1>\"
        },
        \"provider\": \"<aws>\"
      }
    },
  ]
}"
## END DPA ##



###### backup schedule resource ###
####################################
  backup.schedule: 0 */1 * * *
  backup.ttl: 240h0m0s

  # change this to dpa-2 if you want to use a snapshot location other than the one matching the cluster node region
  # dpa-1 matches the  cluster nodes region
  backup.volumeSnapshotLocation: dpa-1
  # list here all applications namespaces you want to backup
  # for example backup.nsToBackup: "[\"pacman-ns\", \"helloworld-pv-ns\"]"
  backup.nsToBackup: "[\"app1-ns\", \"app2-ns\", \"app3-ns\"]" 
######################################
###### end backup schedule resource ###

###### restore resource ###
####################################
  restore.restorePVs: "true"
  # the name of the backup to restore from
  # for example backupName: acm-app-schedule-vb-managed-cls-1-20230208150010
  restore.backupName: <backup-name>
  # list here all apps ns you want to restore from the specified backup
  # for example backup.nsToBackup: "[\"pacman-ns\"]"
  restore.nsToRestore: "[\"app1-ns\", \"app2-ns\"]"
######################################
###### end backup schedule resource ###





