apiVersion: v1
kind: ConfigMap
metadata:
  name: hdr-app-configmap
  namespace: default
data:
  backupNS: acm-app-backup #should not use open-cluster-managemenet-backup
  channel: stable-1.1
  subscriptionName: redhat-oadp-operator
  dpaName: dpa-app #DPA resource name
  dpa.provider: aws
  dpa.backup.cloud.credentials.name: cloud-credentials
  dpa.objectStorage.bucket: <bucket>
  dpa.objectStorage.prefix: <folder>

##AWS
  dpa.aws.backup.cloud.credentials: |
    [default]
    aws_access_key_id=<id>
    aws_secret_access_key=<key>
  dpa.aws.backup.config.region: <us-east-1> # change this if you want to backup resources in a different region
# end AWS

## AZURE
  dpa.azure.backup.cloud.credentials: |
    [backupStorage]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.storage.cloud.credentials: |
    [volumeSnapshot]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.backupLocation.resourceGroup: <azure_resource_group>
  dpa.azure.backupLocation.storageAccount: <azure_storage_account_id>
  dpa.azure.backupLocation.subscriptionId: <azure_subscription_id>
  dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
## end AZURE

###### backup schedule resource ###
####################################
  backup.schedule: 0 */1 * * *
  backup.ttl: 240h0m0s
  includedNamespaces: "[\"pacman-ns\", \"helloworld-pv-ns\"]" # list here all apps ns you want to backup
######################################
###### end backup schedule resource ###




