# This configmap is used by the oadp-hdr-app-install and oadp-hdr-app-backup policies 
# and specifies the configuration required to install velero and create backups 
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: hdr-app-configmap
  namespace: default
data:
  backupNS: acm-app-backup # backupNS should NOT be open-cluster-managemenet-backup
  channel: stable-1.1
  subscriptionName: redhat-oadp-operator

## DPA resource configuration
#
  dpaName: dpa-app #DPA resource name
  dpa.provider: aws
  dpa.backup.cloud.credentials.name: cloud-credentials
  dpa.objectStorage.bucket: <bucket>
  dpa.objectStorage.prefix: <folder>
  ## velero resource limits
  dpa.velero.limits.cpu: "2"
  dpa.velero.limits.memory: 1Gi
  dpa.velero.requests.cpu: 500m
  dpa.velero.requests.memory: 256Mi
##

##AWS
  dpa.aws.backup.cloud.credentials: |
    [default]
    aws_access_key_id=<id>
    aws_secret_access_key=<key>
  dpa.aws.backup.config.region: <region> # for example us-east-1
# end AWS

## AZURE
  dpa.azure.backup.cloud.credentials: |
    [backupStorage]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.storage.cloud.credentials: |
    [volumeSnapshot]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.backupLocation.resourceGroup: <azure_resource_group>
  dpa.azure.backupLocation.storageAccount: <azure_storage_account_id>
  dpa.azure.backupLocation.subscriptionId: <azure_subscription_id>
  dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
## end AZURE

###### backup schedule resource ###
####################################
  backup.schedule: 0 */1 * * *
  backup.ttl: 240h0m0s
  includedNamespaces: "[\"pacman-ns\", \"helloworld-pv-ns\"]" # list here all apps ns you want to backup
######################################
###### end backup schedule resource ###




