apiVersion: v1
kind: ConfigMap
metadata:
  name: hdr-app-configmap
  namespace: default
data:
  backupNS: acm-app-backup #should not use open-cluster-managemenet-backup
  channel: stable-1.1
  subscriptionName: redhat-oadp-operator
  dpaName: dpa-app #DPA resource name
  dpa.provider: aws
  dpa.backup.cloud.credentials.name: cloud-credentials
  dpa.objectStorage.bucket: <bucket_name>
  dpa.objectStorage.prefix: <folder_in_bucket>
## AZURE
  dpa.azure.backup.cloud.credentials: |
    [backupStorage]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.storage.cloud.credentials: |
    [volumeSnapshot]
    dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
  dpa.azure.backupLocation.resourceGroup: <azure_resource_group>
  dpa.azure.backupLocation.storageAccount: <azure_storage_account_id>
  dpa.azure.backupLocation.subscriptionId: <azure_subscription_id>
  dpa.azure.backupLocation.storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
## end AZURE
##AWS
  dpa.aws.backup.profile.name: backupStorage
  dpa.aws.snapshot.profile.name: volumeSnapshot
  # should use above dpa.aws.backup.profile.name and dpa.aws.storage.profile.name
  dpa.aws.backup.cloud.credentials: |
    [backupStorage]
    aws_access_key_id=<aws_access_key_id>
    aws_secret_access_key=<aws_secret_access_key>
    [volumeSnapshot]
    aws_access_key_id=<aws_access_key_id>
    aws_secret_access_key=<aws_secret_access_key>
  dpa.aws.backup.config.region: <us-east-1>
  dpa.aws.snapshot.config.region: <us-east-1>
# end AWS
###### backup schedule resource ###
  backup.schedule: 0 */1 * * *
  backup.ttl: 240h0m0s
###### end backup schedule resource ###




