# This policy creates a velero restore resource to all managed clusters 
# with a label "acm-app-hdr=restore". The restore resource is used to restore applications resources and PVs
# from a selected backup.
# The restore uses the includedNamespaces property to specify the namespaces for the applications to restore 
#
# Note that it is set to enforce by default.
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oadp-hdr-app-restore
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-ns-backup
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-restore-resource
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Restore
                metadata:
                  name: 'restore-{{hub fromConfigMap "" "hdr-app-configmap" "backupName" hub}}'
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                  labels:
                    cluster-id: '{{ fromClusterClaim "id.openshift.io" }}'
                    cluster-name: '{{ fromClusterClaim "name" }}'
                spec:
                  includedNamespaces: '{{hub fromConfigMap "" "hdr-app-configmap" "nsToRestore" | toLiteral hub}}'
                  backupName: '{{hub fromConfigMap "" "hdr-app-configmap" "backupName" hub}}'
                  restorePVs: '{{hub fromConfigMap "" "hdr-app-configmap" "restorePVs" | toBool hub}}' 
                status:
                  phase: Completed            
          remediationAction: enforce
          severity: high
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: oadp-hdr-app-restore-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: acm-app-hdr
        operator: In
        values:
          - restore
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oadp-hdr-app-restore-placement-binding
  namespace: default
placementRef:
  name: oadp-hdr-app-restore-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: oadp-hdr-app-restore
    apiGroup: policy.open-cluster-management.io
    kind: Policy