# This policy deploys velero using the OADP operator to all managed clusters 
# with a label "acm-app-hdr in [backup, restore]".
#
# Note that it is set to enforce by default.
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oadp-hdr-app-install
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-4 Backups of information are conducted maintained and tested
    policy.open-cluster-management.io/standards: NIST-CSF
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-ns-oadp-operators
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-oadp-operator-group
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: redhat-oadp-operator-group
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                spec:
                  targetNamespaces:
                    - '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-oadp-operator-subscription
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: redhat-oadp-operator-subscription
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                spec:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "subscriptionName" hub}}'
                  channel: '{{hub fromConfigMap "" "hdr-app-configmap" "channel" hub}}'
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-backup-storage-credentials-secret
        spec:
          object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              data:
                cloud: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.aws.backup.cloud.credentials" | base64enc hub}}'
              kind: Secret
              metadata:
                name: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.backup.cloud.credentials.name" hub}}'
                namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
              type: Opaque
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-oadp-dpa-resource
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: oadp.openshift.io/v1alpha1
                kind: DataProtectionApplication
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "dpaName" hub}}'
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                spec:
                  backupLocations:
                    - velero:
                        default: true
                        credential:
                          key: cloud
                          name: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.backup.cloud.credentials.name" hub}}'
                        config: 
                          profile: default
                          region: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.aws.backup.config.region" hub}}'
                        objectStorage:
                          bucket: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.objectStorage.bucket" hub}}'
                          prefix: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.objectStorage.prefix" hub}}'
                        provider: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.provider" hub}}'
                  configuration:
                    restic:
                      enable: false
                    velero:
                      podConfig:
                        resourceAllocations:
                          limits:
                            cpu: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.velero.limits.cpu" hub}}'
                            memory: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.velero.limits.memory" hub}}'
                          requests:
                            cpu: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.velero.requests.cpu" hub}}'
                            memory: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.velero.requests.memory" hub}}'                   
                      defaultPlugins:
                        - openshift
                        - '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.provider" hub}}'
                  snapshotLocations:
                    - velero:
                        config: 
                          profile: default
                          region: '{{ fromClusterClaim "region.open-cluster-management.io" }}'
                        provider: '{{hub fromConfigMap "" "hdr-app-configmap" "dpa.provider" hub}}'
          remediationAction: enforce
          severity: high
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: oadp-hdr-app-install-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: acm-app-hdr
        operator: In
        values:
          - backup
          - restore
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oadp-hdr-app-install-placement-binding
  namespace: default
placementRef:
  name: oadp-hdr-app-install-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: oadp-hdr-app-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy