apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: oadp-hdr-app-backup
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-ns-backup
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: check-schedule-resource
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: velero.io/v1
                kind: Schedule
                metadata:
                  name: 'acm-app-schedule-{{ fromClusterClaim "name" }}'
                  namespace: '{{hub fromConfigMap "" "hdr-app-configmap" "backupNS" hub}}'
                  labels:
                    cluster-id: '{{ fromClusterClaim "id.openshift.io" }}'
                    cluster-name: '{{ fromClusterClaim "name" }}'
                spec:
                  schedule: '{{hub fromConfigMap "" "hdr-app-configmap" "backup.schedule" hub}}' 
                  template:
                    snapshotVolumes: true
                    includedNamespaces: 
                    - '{{hub fromConfigMap "" "hdr-app-configmap" "includedNamespaces" hub}}' 
                    ttl: '{{hub fromConfigMap "" "hdr-app-configmap" "backup.ttl" hub}}' 
                status:
                  phase: Enabled                
          remediationAction: enforce
          severity: high
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: oadp-hdr-app-backup-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions:
      - key: acm-backup
        operator: In
        values:
          - acm-hdr-app
      - key: vendor
        operator: In
        values:
          - OpenShift
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: oadp-hdr-app-backup-placement-binding
  namespace: default
placementRef:
  name: oadp-hdr-app-backup-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: oadp-hdr-app-backup
    apiGroup: policy.open-cluster-management.io
    kind: Policy